name: geoai
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _x86_64-microarch-level=4
  - affine=2.4.0
  - alsa-lib=1.2.15.3
  - archspec=0.2.5
  - attr=2.5.2
  - attrs=25.4.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.21.0
  - aws-c-mqtt=0.13.1
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - backports.zstd=1.3.0
  - blosc=1.21.6
  - boltons=25.0.0
  - branca=0.8.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - capnproto=1.2.0
  - ceres-solver=2.2.0
  - certifi=2026.1.4
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - conda=24.11.3
  - conda-libmamba-solver=24.9.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - contourpy=1.3.2
  - cpd=0.5.5
  - cpp-expected=1.3.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - distro=1.9.0
  - docutils=0.22.4
  - double-conversion=3.3.1
  - draco=1.5.7
  - eigen=3.4.0
  - expat=2.7.4
  - fgt=0.4.11
  - fiona=1.10.1
  - fmt=11.1.4
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.17.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - freexl=2.0.0
  - frozendict=2.4.7
  - gdal=3.10.3
  - geopandas=1.1.2
  - geopandas-base=1.1.2
  - geos=3.13.1
  - geotiff=1.7.4
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=11.4.5
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - jinja2=3.1.6
  - joblib=1.5.3
  - json-c=0.18
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - laspy=2.7.0
  - lazrs-python=0.8.1
  - lcms2=2.18
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250127.1
  - libaec=1.1.5
  - libamd=3.3.3
  - libarchive=3.8.1
  - libarrow=20.0.0
  - libarrow-acero=20.0.0
  - libarrow-dataset=20.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcap=2.77
  - libcblas=3.11.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libclang-cpp20.1=20.1.8
  - libclang13=21.1.0
  - libcolamd=3.3.4
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.18.0
  - libcxsparse=4.4.1
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.4
  - libfabric=2.4.0
  - libfabric1=2.4.0
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgdal-arrow-parquet=3.10.3
  - libgdal-core=3.10.3
  - libgdal-hdf5=3.10.3
  - libgdal-pg=3.10.3
  - libgdal-postgisraster=3.10.3
  - libgdal-tiledb=3.10.3
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libklu=2.3.5
  - libkml=1.3.0
  - liblapack=3.11.0
  - libldl=3.3.2
  - libllvm20=20.1.8
  - libllvm21=21.1.0
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libmamba=1.5.12
  - libmambapy=1.5.12
  - libnghttp2=1.67.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=20.0.0
  - libparu=1.0.0
  - libpciaccess=0.18
  - libpdal=2.8.4
  - libpdal-arrow=2.8.4
  - libpdal-core=2.8.4
  - libpdal-cpd=2.8.4
  - libpdal-draco=2.8.4
  - libpdal-e57=2.8.4
  - libpdal-hdf=2.8.4
  - libpdal-icebridge=2.8.4
  - libpdal-nitf=2.8.4
  - libpdal-pgpointcloud=2.8.4
  - libpdal-tiledb=2.8.4
  - libpdal-trajectory=2.8.4
  - libpmix=5.0.8
  - libpng=1.6.55
  - libpq=17.6
  - libprotobuf=5.29.3
  - librbio=4.3.4
  - libre2-11=2025.06.26
  - librttopo=1.1.0
  - libsolv=0.7.35
  - libspatialite=5.1.0
  - libspex=3.2.3
  - libspqr=4.3.4
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsuitesparseconfig=7.10.1
  - libsystemd0=257.10
  - libthrift=0.21.0
  - libtiff=4.7.1
  - libudev1=257.10
  - libumfpack=6.3.5
  - libutf8proc=2.10.0
  - libuuid=2.41.3
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - m2r2=0.3.4
  - mamba=1.5.12
  - mapclassify=2.8.1
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - menuinst=2.4.2
  - metis=5.1.0
  - minizip=4.0.10
  - mistune=0.8.4
  - mpfr=4.2.1
  - mpi=1.0.1
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.4.2
  - nitro=2.7.dev8
  - nlohmann_json=3.12.0
  - nlohmann_json-abi=3.12.0
  - numpy=2.2.6
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openmpi=5.0.8
  - openssl=3.6.1
  - orc=2.1.2
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.45
  - pdal=2.8.4
  - pillow=12.1.1
  - pip=26.0.1
  - pixman=0.46.4
  - platformdirs=4.9.2
  - pluggy=1.6.0
  - postgresql=17.6
  - proj=9.6.2
  - prometheus-cpp=1.3.0
  - pthread-stubs=0.3
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pyogrio=0.11.0
  - pyparsing=3.3.2
  - pyproj=3.7.1
  - pyside6=6.9.2
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-pdal=3.4.5
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.9.2
  - rasterio=1.4.3
  - rdma-core=61.0
  - re2=2025.06.26
  - readline=8.3
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.5
  - ruamel.yaml=0.18.17
  - ruamel.yaml.clib=0.2.15
  - s2n=1.5.22
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - setuptools=80.10.2
  - shapely=2.1.1
  - simdjson=4.2.4
  - six=1.17.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - spdlog=1.15.3
  - sqlite=3.51.1
  - suitesparse=7.10.1
  - threadpoolctl=3.6.0
  - tiledb=2.28.0
  - tk=8.6.15
  - tornado=6.5.3
  - tqdm=4.67.3
  - truststore=0.10.4
  - tzcode=2025c
  - tzdata=2025c
  - ucc=1.6.0
  - ucx=1.19.1
  - unicodedata2=17.0.1
  - uriparser=0.9.8
  - urllib3=2.5.0
  - wayland=1.24.0
  - wheel=0.46.3
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.5
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.7
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.7
  - xorg-xorgproto=2024.1
  - xyzservices=2025.11.0
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - yaml-cpp=0.8.0
  - zlib=1.3.1
  - zlib-ng=2.3.3
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - pdal-plugins==1.6.2
prefix: /home/sharon/miniconda3/envs/geoai
